name: summarize-change
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - numpy=2.0.*
  - pandas=2.3.*
  - matplotlib=3.10.*
  - scikit-learn=1.7.*
  - scipy=1.16.*
  - numba
  - numexpr
  - rasterio=1.4.*
  - pyproj=3.6.*
  - pillow
  - tqdm
  - xlsxwriter
  - matplotlib-scalebar
  - pip
  - pip:
      - cartopy==0.25.0
      - shapely==2.1.1
      - pyshp==2.3.1
      - great-circle-calculator==1.3.1
      - matplotlib-map-utils==3.1.0
